aspect:
  enabled: true

spring:
  codec:
    max-in-memory-size: 10MB
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/ext_api_db
    username: test_user
    password: password
  liquibase:
    url: jdbc:postgresql://localhost:5433/ext_api_db
    user: test_user
    password: password

api:
  external:
    ref-data-url: https://api.iex.cloud/v1/data/CORE/REF_DATA?token=%s
    stock-data-url: https://api.iex.cloud/v1/data/core/quote/%s?token=%s
    token: pk_f257ae699e7d4878a31a0bc8a8dac835

service:
  number-of-companies: 200
